# Generated by Django 5.0.1 on 2024-05-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carsone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('model', models.DateField()),
                ('type', models.CharField(max_length=400)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=4000)),
                ('img', models.ImageField(upload_to='photo')),
                ('speed', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=100)),
                ('horspwoer', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Carstwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('model', models.DateField()),
                ('type', models.CharField(max_length=400)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=4000)),
                ('img', models.ImageField(upload_to='photo')),
                ('speed', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=100)),
                ('horspwoer', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Conect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('message', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Serves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='photo')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=5000)),
            ],
        ),
    ]
