# Generated by Django 5.0.1 on 2024-05-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsone',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carstwo',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
